# Generated by Django 3.2.7 on 2021-09-23 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='House Name')),
            ],
            options={
                'verbose_name': 'house',
                'db_table': 't_house',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('house',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.house')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'student',
                'db_table': 't_student',
                'ordering': ['age'],
            },
        ),
    ]
