# Generated by Django 3.2.7 on 2021-09-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Join Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', upload_to='images',
                                    width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='student',
            name='logo_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='logo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'age', 'house')},
        ),
    ]
