# Generated by Django 3.2.7 on 2021-09-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0002_auto_20210923_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('grade', models.IntegerField(verbose_name='Minimum Grade Required')),
                ('students',
                 models.ManyToManyField(db_table='t_student_course', related_name='courses', to='mainapp.Student',
                                        verbose_name='Students took this course')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'course',
                'db_table': 't_course',
            },
        ),
    ]
