# Generated by Django 3.2.7 on 2021-09-28 23:56

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.IntegerField(verbose_name='Year taking this course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[mainapp.models.StudentValidator.valid_age]),
        ),
        migrations.AlterField(
            model_name='student',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', upload_to='storage', width_field='logo_width'),
        ),
    ]
