# Generated by Django 3.2.7 on 2021-10-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210928_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='mainapp.house'),
        ),
    ]
